apps/Blog/urls.py
from django.urls import path

from .views import (
    BlogDetailPage,
    BlogPage,
    BlogDetailLeaveReaply,
    PicturesPage,
    UserPostCreatePage,
    UserPostUpdatePage,
    UserPostDeletePage,
    UserPostsPage,
)


app_name = "blog"
urlpatterns = [
    path("blog-update-post/<int:pk>", UserPostUpdatePage.as_view(), name="update-post"),
    path("blog-delete-post/<int:pk>", UserPostDeletePage.as_view(), name="delete-post"),
    path("blog-detail/<int:pk>", BlogDetailPage.as_view(), name="blog-detail"),
    path("blog-create-post/", UserPostCreatePage.as_view(), name="create-post"),
    path("blog-home/", BlogPage.as_view(), name="blog"),
    path(
        "blog-detail-comment-write/<int:pk>",
        BlogDetailLeaveReaply.as_view(),
        name="comment-write",
    ),
    path("blog-pictures/", PicturesPage.as_view(), name="pictures"),
    path("blog-my-posts", UserPostsPage.as_view(), name="my-posts"),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.news.urls")),
    path("blog/", include("apps.Blog.urls")),
    path("users/", include("apps.users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL)

apps/Blog/forms.py
from django import forms
from apps.shared.models import AnonimusUserEmails
from .models import Comment, Post


class SaveAnonimousUserEmailForm(forms.ModelForm):
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "email",
                "class": "form-control",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Enter email'",
                "placeholder": "Enter email",
                "required": None,
            }
        )
    )

    class Meta:
        model = AnonimusUserEmails
        fields = ("email",)


class WriteCommentForm(forms.ModelForm):
    message = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control w-100",
                "name": "comment",
                "id": "comment",
                "cols": "30",
                "rows": "9",
            }
        )
    )

    class Meta:
        model = Comment
        fields = ("message",)


class CreatePostForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "name": "title",
                "placeholder": "Title",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Title'",
            }
        )
    )
    descriptions = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "name": "descriptions",
                "placeholder": "Descriptions",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Descriptions'",
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "type": "text",
                "name": "content",
                "placeholder": "Content",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Content'",
            }
        )
    )
    content_image = forms.FileField(
        widget=forms.FileInput(
            attrs={
                "type": "file",
                "name": "content_image",
                "placeholder": "Post image",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Post image'",
            }
        )
    )
    is_active = forms.BooleanField()

    class Meta:
        model = Post
        fields = (
            "title",
            "descriptions",
            "content",
            "categories",
            "tags",
            "content_image",
            "is_active",
        )


class UpdatePostForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "name": "title",
                "placeholder": "Title",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Title'",
            }
        )
    )
    descriptions = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "type": "text",
                "name": "descriptions",
                "placeholder": "Descriptions",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Descriptions'",
            }
        )
    )
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "type": "text",
                "name": "content",
                "placeholder": "Content",
                "class": "single-input",
                "onfocus": "this.placeholder = ''",
                "onblur": "this.placeholder = 'Content'",
            }
        )
    )
    # content_image = forms.FileField(widget=forms.FileInput(attrs={
    #     "type":"file", "name":"content_image", "placeholder":"Post image", "class":"single-input",
    #     "onfocus":"this.placeholder = ''", "onblur":"this.placeholder = 'Post image'"
    # }))
    is_active = forms.BooleanField()

    class Meta:
        model = Post
        fields = (
            "title",
            "descriptions",
            "content",
            "categories",
            "tags",
            "content_image",
            "is_active",
        )

apps/Blog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.views import View
from django.contrib import messages
from django.urls import reverse


from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from .models import Post, Categories, Tag, Comment
from .forms import (
    SaveAnonimousUserEmailForm,
    WriteCommentForm,
    CreatePostForm,
    UpdatePostForm,
)

from apps.shared.models import Pictures

import markdown2

class BlogPage(View):

    def get(self, request):
        context = {}

        if request.user.is_authenticated:
            posts = Post.objects.exclude(user=request.user).filter(is_active=True)
        else:
            posts = Post.objects.filter(is_active=True)

        posts = posts.order_by("-created_at")

        categories = Categories.objects.all()
        tags = Tag.objects.all()
        form = SaveAnonimousUserEmailForm()

        page = request.GET.get("page", 1)
        size = request.GET.get("size", 4)

        # Paginating
        pagination = Paginator(posts, size)
        page_obj = pagination.page(page)

        context["page_obj"] = page_obj
        context["posts"] = page_obj
        context["recent_posts"] = posts
        context["categories"] = categories
        context["tags"] = tags
        context["form"] = form

        # searching
        param = request.GET.get("q", None)
        if param is not None:
            response_param = Post.objects.filter(title__icontains=param)
            context["posts"] = response_param

        # searching in categories
        categori = request.GET.get("categoriy", None)
        if categori is not None:
            if request.user.is_authenticated:
                response_categori = Post.objects.exclude(user=request.user).filter(
                    categories=categories.get(name=categori)
                )
            else:
                response_categori = Post.objects.filter(
                    categories=categories.get(name=categori)
                )

            context["posts"] = response_categori

        # searching in tags
        tag = request.GET.get("tag", None)
        if tag is not None:
            if request.user.is_authenticated:
                response_tag = Post.objects.exclude(user=request.user).filter(
                    tags=tags.get(name=tag)
                )
            else:
                response_tag = Post.objects.filter(tags=tags.get(name=tag))

            context["posts"] = response_tag

        # searching in user posts
        post_user_id = request.GET.get("user", None)
        if post_user_id is not None:
            posts = Post.objects.filter(user=post_user_id)
            return render(request, "blog/blog.html", {"posts": posts})

        return render(request, "blog/blog.html", context)

    def post(self, request):

        form = SaveAnonimousUserEmailForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "You successfully saved email senk you")
            return redirect("blog:blog")
        else:
            messages.error(request, "It is email already token!")
            return redirect("blog:blog")


class BlogDetailPage(View):

    def get(self, request, pk):
        context = {}
        posts = Post.objects.all()
        categories = Categories.objects.all()
        tags = Tag.objects.all()
        post = posts.get(pk=pk)
        comments = Comment.objects.filter(post=post)

        form = SaveAnonimousUserEmailForm()
        comment_form = WriteCommentForm()

        context["post"] = post
        context['content_html'] = markdown2.markdown(post.content)
        
        context["comment_form"] = comment_form

        if request.user.is_authenticated:
            context["recent_posts"] = (
                posts.exclude(id=post.id)
                .filter(user=request.user)
                .order_by("-created_at")
            )
        else:
            context["recent_posts"] = (
                posts.exclude(id=post.id)
                .filter(categories=post.categories)
                .order_by("-created_at")
            )

        context["categories"] = categories
        context["tags"] = tags
        context["form"] = form
        context["comments"] = comments

        # searching
        param = request.GET.get("q", None)
        if param is not None:
            response_param = Post.objects.filter(title__icontains=param)
            context["posts"] = response_param

        # searching in categories
        categori = request.GET.get("categoriy", None)
        if categori is not None:
            print(categori)
            response_categori = Post.objects.filter(
                categories=categories.get(name=categori)
            )
            context["posts"] = response_categori

        # searching in tags
        tag = request.GET.get("tag", None)
        if tag is not None:
            response_tag = Post.objects.filter(tags=tags.get(name=tag))
            context["posts"] = response_tag

        # searching in user posts
        post_user_id = request.GET.get("user", None)
        if post_user_id is not None:
            posts = Post.objects.filter(user=post_user_id)
            return render(request, "blog/blog.html", {"posts": posts})

        return render(request, "blog/single-blog.html", context)

    def post(self, request, pk):

        form = SaveAnonimousUserEmailForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "You successfully saved email senk you")
            return redirect("blog:blog")
        else:
            messages.error(request, "It is email already token!")
            return redirect("blog:blog")


class BlogDetailLeaveReaply(View):

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = WriteCommentForm(request.POST)

        if form.is_valid():
            message = form.cleaned_data.get("message")
            Comment.objects.create(post=post, user=request.user, message=message)
            messages.success(request, f"successfully sening message")
            return redirect(reverse("blog:blog"))

        else:
            messages.error(request, "Ow no your message are not valid !")
        return redirect(reverse("blog:blog-blog"))


class UserPostsPage(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        posts = Post.objects.all()
        categories = Categories.objects.all()
        tags = Tag.objects.all()

        page = request.GET.get("page", 1)
        size = request.GET.get("size", 4)

        # Paginating
        pagination = Paginator(posts.filter(user=request.user), size)
        page_obj = pagination.page(page)

        context["posts"] = page_obj
        context["page_obj"] = page_obj
        context["categories"] = categories
        context["recent_posts"] = posts.filter(user=request.user)
        context["tags"] = tags

        return render(request, "blog/my_posts.html", context)


class UserPostCreatePage(LoginRequiredMixin, View):

    def get(self, request):
        context = {}
        user_posts = Post.objects.filter(user=request.user)
        form = CreatePostForm()
        context["form"] = form
        context["user_posts"] = user_posts
        return render(request, "blog/create_post.html", context)

    def post(self, request):
        form = CreatePostForm(data=request.POST, files=request.FILES)
        print(form.data)
        if form.is_valid():
            post = Post.objects.create(
                user=request.user,
                title=form.cleaned_data.get("title"),
                descriptions=form.cleaned_data.get("descriptions"),
                content=form.cleaned_data.get("content"),
                categories=form.cleaned_data.get("categories"),
                tags=form.cleaned_data.get("tags"),
                content_image=form.cleaned_data.get("content_image"),
                is_active=form.cleaned_data.get("is_active"),
            )
            messages.success(request, f"Successfully creted post ({post})")
            return redirect("blog:create-post")
        else:
            messages.error(request, "Your post are not valid !")
            return redirect("blog:create-post")


class UserPostUpdatePage(LoginRequiredMixin, View):

    def get(self, request, pk):
        context = {}
        post = Post.objects.get(pk=pk)
        form = UpdatePostForm(instance=post)
        context["form"] = form
        context["post"] = post
        return render(request, "blog/update_post.html", context)

    def post(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = UpdatePostForm(data=request.POST, instance=post, files=request.FILES)
        print(form.data)
        if form.is_valid():
            form.save()
            messages.success(request, f"You successfully updated post ( {post.title} )")
            return redirect(reverse("blog:my-posts"))

        else:
            messages.error(request, "Pleace enter valid post configurations !")
            return redirect(reverse("blog:update-post", kwargs={"pk": post.pk}))


class UserPostDeletePage(LoginRequiredMixin, View):

    def get(self, request, pk):
        context = {}
        post = Post.objects.get(pk=pk)
        context["post"] = post
        return render(request, "blog/delete_post.html", context)

    def post(self, request, pk):

        post = Post.objects.get(pk=pk)
        post.delete()
        messages.success(request, "You are successfully deleted Post")
        return redirect(reverse("blog:my-posts"))


class PicturesPage(View):

    def get(self, request):
        context = {}
        pictures = Pictures.objects.all()

        page = request.GET.get("page", 1)
        size = request.GET.get("size", 12)

        pagination = Paginator(pictures, size)
        page_obj = pagination.page(page)

templates/blog/blog.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} Blog Post {% endblock %}
{% block content %}
    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">
                        {% for post in posts %}
                        <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{ post.content_image.url }}" alt="">
                                <a href="{% url 'blog:blog-detail' post.pk %}" class="blog_item_date">
                                    <h3>{{ post.created_at }}</h3>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'blog:blog-detail' post.pk %}">
                                    <h2>{{ post.title }}</h2>
                                </a>
                                <p>{{ blog.descriptions }}</p>
                                <ul class="blog-info-link">
                                    <li><a href="{% url 'blog:blog' %}?user={{ post.user.id }}"><i class="fa fa-user"></i>{{ post.user }}</a></li>
                                    <li><a href="{% url 'blog:blog-detail' post.pk %}"><i class="fa fa-comments"></i> {{ post.comment_count }} Comments</a></li>
                                </ul>
                            </div>
                        </article>
                        {% empty %}
                        <p><h2>Now content posts</h2></p>
                        {% endfor %}
                        {% include 'includes/blog_paginations.html' %}
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        {% include 'includes/blog/blog_right_sidebar.html' %}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->
{% endblock %}

templates/blog/delete_post.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} Delete Post {% endblock %}
{% block content %}
<div class="container">
    <div class="mt-90 mb-50">
        <center>
            <h2>Your are deleted Post "{{ post.title }}" ?</h2>
            <div class="mt-90">
                <form action="{% url 'blog:delete-post' post.pk %}" method="post">
                    {% csrf_token %}
                        <button class="genric-btn primary-border circle arrow" type="submit">
                            Yes
                            <span class="lnr lnr-arrow-right">
                            </span>
                        </button>
                </form>
            </div>
            <div class="mt-10">
                <a href="{% url 'blog:my-posts' %}" class="genric-btn primary-border circle arrow">Now<span class="lnr lnr-arrow-right"></span></a>
            </div>
        </center>
    </div>
</div>

{% endblock %}

templates/blog/my_posts.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} My Posts {% endblock %}
{% block content %}
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="mt-10 mb-30"><h1>My Posts</h1></div>
                <div class="blog_left_sidebar">
                    {% for post in posts %}
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{ post.content_image.url }}" alt="">
                            <a href="{% url 'blog:blog-detail' post.pk %}" class="blog_item_date">
                                <h3>{{ post.created_at }}</h3>
                            </a>
                        </div>
                        <div class="blog_details">
                            <a class="d-inline-block" href="{% url 'blog:blog-detail' post.pk %}">
                                <h2>{{ post.title }}</h2>
                            </a>
                            <p>{{ blog.descriptions }}</p>
                            <ul class="blog-info-link">
                                <li><a href="{% url 'blog:blog' %}?categoriy={{ post.categories }}"><i class="fa fa-user"></i>{{ post.categories }}</a></li>
                                <li><a href="{% url 'blog:blog-detail' post.pk %}"><i class="fa fa-comments"></i> {{ post.comment_count }} Comments</a></li>
                            </ul>
                        </div>
                    </article>
                    {% empty %}
                    <p><h2>Now content posts</h2></p>
                    {% endfor %}
                    {% include 'includes/blog_paginations.html' %}
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    {% include 'includes/blog/blog_right_sidebar.html' %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/blog/single-blog.html
{% extends 'news/base.html' %}
{% load static %}
{% block title %} Posts {% endblock %}
{% block content %}
   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{ post.content_image.url }}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>
                        {{ post.title }}
                     </h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="{% url 'blog:blog' %}?user={{ post.user.id }}"><i class="fa fa-user"></i> {{ post.user }}</a></li>
                        <li><a href="{% url 'blog:blog-detail' post.pk %}"><i class="fa fa-comments"></i> {{ post.comment_count }} Comments</a></li>
                     </ul>
                     <div class="quote-wrapper">
                        <div class="quotes">
                           {{ post.descriptions }}
                        </div> 
                     </div>
                     <p class="excert">
                        {{ post.content }}
                        <h1>{{ content_html|safe }}</h1>
                     </p>
                  </div>
                  {% if request.user == post.user %}
                     <div class="mt-10 mb-3">
                           <a href="{% url 'blog:delete-post' post.pk %}" class="btn mt-10 mb-3 col-lg-4">delete</a>
                           <a href="{% url 'blog:update-post' post.pk %}" class="btn mt-10 mb-3 col-lg-4">update</a>
                     </div>
                  {% endif %}
               </div>
               <div class="navigation-top">
                  <div class="d-sm-flex justify-content-between text-center">
                     <p class="like-info">
                        <span class="align-middle"><i class="fa fa-heart"></i></span> 
                        Lily and 4
                        people like this</p>
                     <div class="col-sm-4 text-center my-2 my-sm-0">
                        <p class="comment-count"><span class="align-middle"><i class="fa fa-comment"></i></span> {{ post.comment_count }} Comments</p>
                     </div>
                     <ul class="social-icons">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fab fa-behance"></i></a></li>
                     </ul>
                  </div>
               </div>
               
               <div class="blog-author">
                  <div class="media align-items-center">
                     <img src="{{ post.user.avatar.url }}" alt="">
                     <div class="media-body">
                        <a href="#">
                           <h4>{{ post.user }}</h4>
                        </a>
                        {% if post.user.bio %}
                           <p>{{ post.user.bio }}</p>
                        {% endif %}
                     </div>
                  </div>
               </div>

               {% if request.user.is_authenticated %}
                  <div class="comment-form">
                     <h4>Leave a Reply</h4>
                     <form class="form-contact comment_form" action="{% url 'blog:comment-write' post.pk %}" id="commentForm" method="post">
                        {% csrf_token %}
                        <div class="row">
                           <div class="col-12">
                              <div class="form-group">
                                    {{ comment_form.message }}
                              </div>
                           </div>
                        </div>
                        <div class="form-group">
                           <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
                        </div>
                     </form>
                  </div>
               {% endif %}

               <div class="comments-area">
                  <h4>{{ post.comment_count }} Comments</h4>

                  {% for comment in comments %}
                     <div class="comment-list">
                        <div class="single-comment justify-content-between d-flex">
                           <div class="user justify-content-between d-flex">
                              <div class="thumb">
                                 <img src="{{ comment.user.avatar.url }}" alt="">
                              </div>
                              <div class="desc">
                                 <p class="comment">
                                    {{ comment.message }}
                                 </p>
                                 <div class="mt-3 mb-3">
                                    {% if request.user == comment.user %}
                                       <a href="#" class="btn-success col-md-3" >update</a>
                                       <a href="#" class="btn-danger col-md-3">delete</a>
                                    {% endif %}
                                 </div>
                                 <div class="d-flex justify-content-between">
                                    <div class="d-flex align-items-center">
                                       <h5>
                                          <a href="#">{{ comment.user }}</a>
                                       </h5>
                                       <p class="date">{{ comment.created_at }}</p>
                                    </div>
                                    <div class="reply-btn">
                                       <a href="#" class="btn-reply text-uppercase">reply</a>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  {% empty %}
                     <p><h2>Now comment</h2></p>
                  {% endfor %}
               </div>

            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  {% include 'includes/blog/blog_right_sidebar.html' %}

                  <aside class="single_sidebar_widget instagram_feeds">
                     <h4 class="widget_title">Instagram Feeds</h4>
                     <ul class="instagram_row flex-wrap">
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_5.png' %}" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_6.png' %}" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_7.png' %}" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_8.png' %}" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_9.png' %}" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="{% static 'img/post/post_10.png' %}" alt="">
                           </a>
                        </li>
                     </ul>
                  </aside>
                  
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->
{% endblock %}